### ISSUE TITLE
Doesnt compile on UE5.3.2

### ISSUE THREAD

**Issue by Arise** [VesCodes/ImGui#2]
It complains about 
```
Severity	Code	Description	Project	File	Line	Suppression State
Error	C2039	'KeysDown': is not a member of 'ImGuiIO'	MyFirstProject	C:\Users\Neon\Documents\Unreal Projects\MyFirstProject\Plugins\UnrealImGui\Source\ImGui\Private\ImGuiInteroperability.h	25	
Error	C2039	'NavInputs': is not a member of 'ImGuiIO'	MyFirstProject	C:\Users\Neon\Documents\Unreal Projects\MyFirstProject\Plugins\UnrealImGui\Source\ImGui\Private\ImGuiInteroperability.h	26	
Error	C2039	'KeyMap': is not a member of 'ImGuiIO'	MyFirstProject	C:\Users\Neon\Documents\Unreal Projects\MyFirstProject\Plugins\UnrealImGui\Source\ImGui\Private\ImGuiInteroperability.h	28	

```
Checked and KeysDown is not defined in ImGuiIO. Do you used another version?

Found this after testing other versions like benui-dev and IDI-Systems and those worked fine.

**Comment by Arise** [comment]
Oh, bad bug report. I think I copied your files over other imgui projects and those contained ImGuiInteroperability.h file.
Your version is not.
My bad.

**Comment by VesCodes** [comment]
No worries! Worth noting that this plugin has explicitly disabled deprecated ImGui functionality - you can opt out of that if you wish to still use these by removing the `IMGUI_DISABLE_OBSOLETE_FUNCTIONS` and `IMGUI_DISABLE_OBSOLETE_KEYIO` defines in `ImGuiConfig.h`: https://github.com/VesCodes/ImGui/blob/054095b696c4c4d42974461a4c4ff10d5b1e87f6/Source/ImGui/Public/ImGuiConfig.h#L13
